export * from 'constants/setting/settingChangePwdText'
export * from 'constants/setting/SettingMenuText'
export * from 'constants/setting/settingAlarmText'
export * from 'constants/setting/settingNoticeText'
export * from 'constants/setting/settingServiceText'  
