export * from 'components/trades/detail/SecondHandDetailCard'
export * from 'components/trades/detail/PurchaseDetailCard'
export * from 'components/trades/detail/ManagerInfo'
export * from 'components/trades/detail/OtherProducts'
export * from 'components/trades/detail/ImageDetail'
export * from 'components/trades/detail/PurchaseFooter'
export * from 'components/trades/detail/DetailHeader'
export * from 'components/trades/detail/HeaderModal'
export * from 'components/trades/detail/AgreeModal'
export * from 'components/trades/detail/DetailStats'
export * from 'components/trades/detail/Thumbnail'

