export const MODIFY_PROFILE_INPUT_TEXTS = {
  simpleProfileHeaderText: '간단프로필 작성하기',
  modifyProfileHeaderText: '프로필 수정하기',
  emailText: '이메일',
  nameText: '이름',
  phonenumberText: '휴대폰 번호',
  birthText:'생년월일',
  nicknameText: '닉네임',
  bioText: '한 줄 자기소개',
  sexText: '성별',
  sexFemaleText: '여자',
  sexMaleText:'남자',
  positionText: '현재 직급',
  jobText: '직무',
  completeWriteText: '작성완료',
  completeModifytext: '수정완료',
}