export * from 'components/home/NavArea'
export * from 'components/home/Template'
export * from 'components/home/AreaTitle'
export * from 'components/home/Navigation'
export * from 'components/home/MoreNews'
